version: '3.8'

services:
  citus_master:
    image: citusdata/citus:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - master-data:/var/lib/postgresql/data
    networks:
      - citusnet

  citus_worker_1:
    image: citusdata/citus:12.1
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - worker1-data:/var/lib/postgresql/data
    networks:
      - citusnet

  citus_worker_2:
    image: citusdata/citus:12.1
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    volumes:
      - worker2-data:/var/lib/postgresql/data
    networks:
      - citusnet

networks:
  citusnet:

volumes:
  master-data:
  worker1-data:
  worker2-data:
